load("@prysm//tools/go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "blob.go",
        "data_column.go",
        "interval_logger.go",
    ],
    importpath = "github.com/OffchainLabs/prysm/v7/runtime/logging",
    visibility = ["//visibility:public"],
    deps = [
        "//consensus-types/blocks:go_default_library",
        "@com_github_sirupsen_logrus//:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = ["interval_logger_test.go"],
    embed = [":go_default_library"],
    deps = [
        "@com_github_pkg_errors//:go_default_library",
        "@com_github_sirupsen_logrus//:go_default_library",
        "@com_github_stretchr_testify//require:go_default_library",
    ],
)
